
# ===================================== COPYRIGHT ===================================== #
#                                                                                       #
#                           ***** R3M Research Project *****                            #
#                                                                                       #
#  Reconfigurable Robotics for Responsive Manufacture (R3M) is a three-year research    #
#  project co-funded by the EPSRC and a group of Universities in the UK. The project    #
#  aims to develop new methods to enable the rapid and automated configuration of       #
#  robot manufacturing cells to allow mixed and variable products and processes to be   #
#  performed using the same basic hardware, the R3M Cell.                               #
#                                                                                       #
#  Licensed under the Apache-2.0 License.                                               #
#  You may not use this file except in compliance with the License.                     #
#  You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0  #
#                                                                                       #
#  Unless required by applicable law or agreed to in writing, software distributed      #
#  under the License is distributed on an "as-is" basis, without warranties or          #
#  conditions of any kind, either express or implied. See the License for the specific  #
#  language governing permissions and limitations under the License.                    #
#                                                                                       #
#  R3M Project Consortium:                                                              #
#                                                                                       #
#  AUTHORS (Cranfield University):                                                      #
#           Mikel Bueno Viso       - Mikel.Bueno-Viso@cranfield.ac.uk                   #
#           Dr. Seemal Asif        - s.asif@cranfield.ac.uk                             #
#           Prof. Phil Webb        - p.f.webb@cranfield.ac.uk                           #
#                                                                                       #
#  AUTHORS (Loughborough University):                                                   #
#           Dr. Paul Anandan       - p.d.anandan2@lboro.ac.uk                           #
#           Dr. Pedro Ferreira     - P.Ferreira@lboro.ac.uk                             #
#           Prof. Niels Lohse      - n.lohse@lboro.ac.uk                                #
#                                                                                       #
#  AUTHORS (Sheffield University):                                                      #
#           Yue Yao                - yue.yao@sheffield.ac.uk                            #
#           Dr. Ze Zhang           - ze.zhang@sheffield.ac.uk                           #
#           Dr. Windo Hutabarat    - w.hutabarat@sheffield.ac.uk                        #
#           Prof. Ashutosh Tiwari  - a.tiwari@sheffield.ac.uk                           #
#                                                                                       #
#  AUTHORS (AMRC - Sheffield):                                                          #
#           Dr. Gautham Ragunathan - g.ragunathan@amrc.co.uk                            #
#           Dr. Lloyd Tinkler      - l.tinkler@amrc.co.uk                               #
#                                                                                       #
#  Date: February, 2025.                                                                #
#                                                                                       #
# ===================================== COPYRIGHT ===================================== #

# ======= CITE OUR WORK ======= #
# You can cite our work with the following statement:
# R3M-Cell (2025) Reconfigurable Robotics for Responsive Manufacture. URL: https://github.com/IFRA-Cranfield/R3M_Cell.

# R3M Cell - AMRC-Sheffield.
Configurations:

  - ID: "r3mcell_amrc_1"
    Name: "ABB IRB1200 + N/A: N/A"
    urdf: "r3mcell_amrc_1.urdf.xacro"
    rob: "irb1200"
    ee: "none"

  - ID: "r3mcell_amrc_11"
    Name: "ABB IRB1200 + Zimmer GP5010NC-00-A: Cube Stacking use-case."
    urdf: "r3mcell_amrc_CuS_1200.urdf.xacro"
    rob: "irb1200"
    ee: "gpp5010nc"
  
  - ID: "r3mcell_amrc_12"
    Name: "ABB IRB1200 + Zimmer GP5010NC-00-A: Cube Kitting use-case."
    urdf: "r3mcell_amrc_CK_1200.urdf.xacro"
    rob: "irb1200"
    ee: "gpp5010nc"

  - ID: "r3mcell_amrc_13"
    Name: "ABB IRB1200 + Zimmer GP5010NC-00-A: Cylinder Stacking use-case."
    urdf: "r3mcell_amrc_CyS_1200.urdf.xacro"
    rob: "irb1200"
    ee: "gpp5010nc"
  
  - ID: "r3mcell_amrc_14"
    Name: "ABB IRB1200 + LS-Vacuum Gripper: Lamination Sheet Pick-and-Place use-case."
    urdf: "r3mcell_amrc_LamStack.urdf.xacro"
    rob: "irb1200"
    ee: "ls_vgr_amrc"

  - ID: "r3mcell_amrc_15"
    Name: "ABB IRB1200 + Zimmer GP5010NC-00-A: R3M-Perception Testing use-case."
    urdf: "r3mcell_amrc_PT.urdf.xacro"
    rob: "irb1200"
    ee: "gpp5010nc"

  - ID: "r3mcell_amrc_2"
    Name: "ABB IRB6640 + N/A: N/A"
    urdf: "r3mcell_amrc_2.urdf.xacro"
    rob: "irb6640"
    ee: "none"

  - ID: "r3mcell_amrc_20"
    Name: "ABB IRB6640 + N/A: ROS 2 Driver testing pipeline."
    urdf: "r3mcell_amrc_BD.urdf.xacro"
    rob: "irb6640"
    ee: "none"

  - ID: "r3mcell_amrc_21"
    Name: "ABB IRB6640 + Zimmer GP5010NC-00-A: Cube Stacking use-case."
    urdf: "r3mcell_amrc_CuS_6640.urdf.xacro"
    rob: "irb6640"
    ee: "gpp5010nc"

  - ID: "r3mcell_amrc_22"
    Name: "ABB IRB6640 + Zimmer GP5010NC-00-A: Cube Kitting use-case."
    urdf: "r3mcell_amrc_CK_6640.urdf.xacro"
    rob: "irb6640"
    ee: "gpp5010nc"

  - ID: "r3mcell_amrc_23"
    Name: "ABB IRB6640 + Zimmer GP5010NC-00-A: Cylinder Stacking use-case."
    urdf: "r3mcell_amrc_CyS_6640.urdf.xacro"
    rob: "irb6640"
    ee: "gpp5010nc"
  
  - ID: "r3mcell_amrc_24"
    Name: "ABB IRB6640 + Zimmer GP5010NC-00-A: Battery Disassembly use-case."
    urdf: "r3mcell_amrc_BD.urdf.xacro"
    rob: "irb6640"
    ee: "gpp5010nc"

  - ID: "r3mcell_amrc_1test"
    Name: "ABB IRB1200 - R3MTesting"
    urdf: "r3mcell_amrc_1.urdf.xacro"
    rob: "irb1200"
    ee: "none"

  - ID: "r3mcell_amrc_2test"
    Name: "ABB IRB6640 - R3MTesting"
    urdf: "r3mcell_amrc_2.urdf.xacro"
    rob: "irb6640"
    ee: "none"