# R3M Cell - CRANFIELD UNIVERSITY.
Configurations:

  - ID: "r3mcell_cu_1"
    Name: "ABB IRB-120 Robot + Schunk EGP-64 Gripper on Cranfield University (IA Lab) Cell."
    urdf: "r3mcell_cu_1.urdf.xacro"
    ee: "egp64"

  - ID: "r3mcell_cu_2"
    Name: "UR3 Robot + Robotiq HandE Gripper on Cranfield University (IA Lab) Stand."
    urdf: "r3mcell_cu_2.urdf.xacro"
    ee: "robotiq_hande"