# R3M Cell - AMRC-Sheffield.
Configurations:

  - ID: "r3mcell_amrc_1"
    Name: "ABB IRB1200 + N/A: N/A"
    urdf: "r3mcell_amrc_1.urdf.xacro"
    rob: "irb1200"
    ee: "none"

  - ID: "r3mcell_amrc_11"
    Name: "ABB IRB1200 + Zimmer GP5010NC-00-A: Cube Stacking use-case."
    urdf: "r3mcell_amrc_CuS_1200.urdf.xacro"
    rob: "irb1200"
    ee: "gpp5010nc"
  
  - ID: "r3mcell_amrc_12"
    Name: "ABB IRB1200 + Zimmer GP5010NC-00-A: Cube Kitting use-case."
    urdf: "r3mcell_amrc_CK_1200.urdf.xacro"
    rob: "irb1200"
    ee: "gpp5010nc"

  - ID: "r3mcell_amrc_13"
    Name: "ABB IRB1200 + Zimmer GP5010NC-00-A: Cylinder Stacking use-case."
    urdf: "r3mcell_amrc_CyS_1200.urdf.xacro"
    rob: "irb1200"
    ee: "gpp5010nc"
  
  - ID: "r3mcell_amrc_14"
    Name: "ABB IRB1200 + LS-Vacuum Gripper: Lamination Sheet Pick-and-Place use-case."
    urdf: "r3mcell_amrc_LamStack.urdf.xacro"
    rob: "irb1200"
    ee: "ls_vgr_amrc"

  - ID: "r3mcell_amrc_2"
    Name: "ABB IRB6640 + N/A: N/A"
    urdf: "r3mcell_amrc_2.urdf.xacro"
    rob: "irb6640"
    ee: "none"

  - ID: "r3mcell_amrc_20"
    Name: "ABB IRB6640 + N/A: ROS 2 Driver testing pipeline."
    urdf: "r3mcell_amrc_BD.urdf.xacro"
    rob: "irb6640"
    ee: "none"

  - ID: "r3mcell_amrc_21"
    Name: "ABB IRB6640 + Zimmer GP5010NC-00-A: Cube Stacking use-case."
    urdf: "r3mcell_amrc_CuS_6640.urdf.xacro"
    rob: "irb6640"
    ee: "gpp5010nc"

  - ID: "r3mcell_amrc_22"
    Name: "ABB IRB6640 + Zimmer GP5010NC-00-A: Cylinder Stacking use-case."
    urdf: "r3mcell_amrc_CyS_6640.urdf.xacro"
    rob: "irb6640"
    ee: "gpp5010nc"
  
  - ID: "r3mcell_amrc_23"
    Name: "ABB IRB6640 + Zimmer GP5010NC-00-A: Battery Disassembly use-case."
    urdf: "r3mcell_amrc_BD.urdf.xacro"
    rob: "irb6640"
    ee: "gpp5010nc"