# R3M Cell - CRANFIELD UNIVERSITY.
Configurations:

  - ID: "r3mcell_cu_1"
    Name: "ABB IRB120 + Schunk EGP64: N/A"
    urdf: "r3mcell_cu_1.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "r3mcell_cu_11"
    Name: "ABB IRB120 + Schunk EGP64: Cube Stacking use-case."
    urdf: "r3mcell_cu_1.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "r3mcell_cu_12"
    Name: "ABB IRB120 + Schunk EGP64: Can Pick-and-Place use-case."
    urdf: "r3mcell_cu_canPP.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "r3mcell_cu_13"
    Name: "ABB IRB120 + LS-Vacuum Gripper: Lamination Sheet Pick-and-Place use-case."
    urdf: "r3mcell_cu_LamStack.urdf.xacro"
    rob: "irb120"
    ee: "ls_vgr"

  - ID: "r3mcell_cu_14"
    Name: "ABB IRB120 + N/A: R3M Perception Testing set-up."
    urdf: "r3mcell_cu_PerceptionTest.urdf.xacro"
    rob: "irb120"
    ee: "none"
  
  - ID: "r3mcell_cu_15"
    Name: "ABB IRB120 + Schunk EGP64: Cylinder Stacking use-case."
    urdf: "r3mcell_cu_cylinderstacking.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "r3mcell_cu_2"
    Name: "UR3 + Robotiq HandE: N/A"
    urdf: "r3mcell_cu_2.urdf.xacro"
    rob: "ur3"
    ee: "robotiq_hande"