
# ===================================== COPYRIGHT ===================================== #
#                                                                                       #
#                           ***** R3M Research Project *****                            #
#                                                                                       #
#  Reconfigurable Robotics for Responsive Manufacture (R3M) is a three-year research    #
#  project co-funded by the EPSRC and a group of Universities in the UK. The project    #
#  aims to develop new methods to enable the rapid and automated configuration of       #
#  robot manufacturing cells to allow mixed and variable products and processes to be   #
#  performed using the same basic hardware, the R3M Cell.                               #
#                                                                                       #
#  Licensed under the Apache-2.0 License.                                               #
#  You may not use this file except in compliance with the License.                     #
#  You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0  #
#                                                                                       #
#  Unless required by applicable law or agreed to in writing, software distributed      #
#  under the License is distributed on an "as-is" basis, without warranties or          #
#  conditions of any kind, either express or implied. See the License for the specific  #
#  language governing permissions and limitations under the License.                    #
#                                                                                       #
#  R3M Project Consortium:                                                              #
#                                                                                       #
#  AUTHORS (Cranfield University):                                                      #
#           Mikel Bueno Viso       - Mikel.Bueno-Viso@cranfield.ac.uk                   #
#           Dr. Seemal Asif        - s.asif@cranfield.ac.uk                             #
#           Prof. Phil Webb        - p.f.webb@cranfield.ac.uk                           #
#                                                                                       #
#  AUTHORS (Loughborough University):                                                   #
#           Dr. Paul Anandan       - p.d.anandan2@lboro.ac.uk                           #
#           Dr. Pedro Ferreira     - P.Ferreira@lboro.ac.uk                             #
#           Prof. Niels Lohse      - n.lohse@lboro.ac.uk                                #
#                                                                                       #
#  AUTHORS (Sheffield University):                                                      #
#           Yue Yao                - yue.yao@sheffield.ac.uk                            #
#           Dr. Ze Zhang           - ze.zhang@sheffield.ac.uk                           #
#           Dr. Windo Hutabarat    - w.hutabarat@sheffield.ac.uk                        #
#           Prof. Ashutosh Tiwari  - a.tiwari@sheffield.ac.uk                           #
#                                                                                       #
#  AUTHORS (AMRC - Sheffield):                                                          #
#           Dr. Gautham Ragunathan - g.ragunathan@amrc.co.uk                            #
#           Dr. Lloyd Tinkler      - l.tinkler@amrc.co.uk                               #
#                                                                                       #
#  Date: February, 2025.                                                                #
#                                                                                       #
# ===================================== COPYRIGHT ===================================== #

# ======= CITE OUR WORK ======= #
# You can cite our work with the following statement:
# R3M-Cell (2025) Reconfigurable Robotics for Responsive Manufacture. URL: https://github.com/IFRA-Cranfield/R3M_Cell.

# R3M Cell - CRANFIELD UNIVERSITY.
Configurations:

  - ID: "r3mcell_cu_1"
    Name: "ABB IRB120 + Schunk EGP64: N/A"
    urdf: "r3mcell_cu_1.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "r3mcell_cu_11"
    Name: "ABB IRB120 + Schunk EGP64: Cube Stacking use-case."
    urdf: "r3mcell_cu_cubestacking.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "r3mcell_cu_12"
    Name: "ABB IRB120 + Schunk EGP64: Coloured Cube Kitting use-case."
    urdf: "r3mcell_cu_cubekitting.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "r3mcell_cu_13"
    Name: "ABB IRB120 + Schunk EGP64: Cylinder Stacking use-case."
    urdf: "r3mcell_cu_cylinderstacking.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "r3mcell_cu_14"
    Name: "ABB IRB120 + Schunk EGP64: Can Pick-and-Place use-case."
    urdf: "r3mcell_cu_canPP.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "r3mcell_cu_15"
    Name: "ABB IRB120 + Schunk EGP64: Battery Disassembly use-case."
    urdf: "r3mcell_cu_BD.urdf.xacro"
    rob: "irb120"
    ee: "egp64"

  - ID: "r3mcell_cu_16"
    Name: "ABB IRB120 + LS-Vacuum Gripper: Lamination Sheet Pick-and-Place use-case."
    urdf: "r3mcell_cu_LamStack.urdf.xacro"
    rob: "irb120"
    ee: "ls_vgr"

  - ID: "r3mcell_cu_99"
    Name: "ABB IRB120 + N/A: R3M Perception Testing set-up."
    urdf: "r3mcell_cu_PerceptionTest.urdf.xacro"
    rob: "irb120"
    ee: "none"

  - ID: "r3mcell_cu_2"
    Name: "UR3 + Robotiq HandE: N/A"
    urdf: "r3mcell_cu_2.urdf.xacro"
    rob: "ur3"
    ee: "robotiq_hande"
  
  - ID: "r3mcell_cu_21"
    Name: "UR3 + Robotiq HandE: Cube Stacking Use-Case."
    urdf: "r3mcell_cu_CSTur.urdf.xacro"
    rob: "ur3"
    ee: "robotiq_hande"

  - ID: "r3mcell_cu_22"
    Name: "UR3 + Robotiq HandE: Coloured Cube Kitting Use-Case."
    urdf: "r3mcell_cu_CKur.urdf.xacro"
    rob: "ur3"
    ee: "robotiq_hande"

  - ID: "r3mcell_cu_23"
    Name: "UR3 + Robotiq HandE: Cylinder Stacking Use-Case."
    urdf: "r3mcell_cu_CSur.urdf.xacro"
    rob: "ur3"
    ee: "robotiq_hande"